---
- name: Updating tomcat hello workld page
  become: true
  hosts: all
  tasks:
  - name: Wait until HTTP status is 200
    uri:
      url: "{{ tomcat_server_address }}"
      return_content: yes
      validate_certs: no
      status_code:
        - 200
    until: uri_output.status == 200
    retries: 24
    delay: 10
    register: uri_output
